name: Best Golfimages ever
favicon: null
layout_spectrum: 0.01701
typography_spectrum: 0.65561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4e668a'
    - '#a7c6db'
    - '#fcfded'
    - '#cc8d5a'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
