name: Best Golfimages ever
favicon: null
layout_spectrum: 0.1406071400269866
typography_spectrum: 0.09613326587714255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6294853249564767
  lightness: 0.34718527109362185
  saturation: 0.2546334962826222
  rhythmicContrast: 0.8304389701224864
purpose: []
